dev:

  bucket: "edgarfile-storage"

  filepath: "/Users/prathyusha/Desktop/pranathi/Assignment2/airflow_edgar/dags/sec-edgar/call_transcripts"

  downloadpath: "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api"

  fetchpath: "/Users/prathyusha/Desktop/pranathi/CSYE7245-Spring2021-Labs/transcript-simulated-api/edgar_download"

  APIKey: "f91e8d2d0a74487dbec98f4b8b302711"

  aws_access_key_id: "AKIA4DTCQWNVOEHGVTH3"

  aws_secret_access_key: "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"

  fileinput:
    object_key: "CompaniesList.csv"
    prefix: "Part4/input"

  stage: 
    object_key: "CompaniesCallData.csv"
    jsonobject_key: "CompaniesData.json"
    prefix: "Part4/stage"
